// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

/// @title HelloWorld
/// @author 0x71pp17
/// @notice A minimal contract that stores a public string
/// @return The stored message visible per getter function automatically generated by `public` state variable
contract HelloWorld {
    // State variable: Declares a string that is publicly accessible
    // 'public' automatically generates a getter function for external reading
    string public ourString = "Hello World";
}   
